/*
 * Bitwise Courses - sample Java code
 * http://www.bitwisecourses.com
 */

/**
 *
 * @author huw
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        calcBtn = new javax.swing.JButton();
        typesBtn = new javax.swing.JButton();
        numRangesBtn = new javax.swing.JButton();
        autoboxBtn = new javax.swing.JButton();
        castBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        calcBtn.setText("Calc");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        typesBtn.setText("Types");
        typesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typesBtnActionPerformed(evt);
            }
        });

        numRangesBtn.setText("Number Ranges");
        numRangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numRangesBtnActionPerformed(evt);
            }
        });

        autoboxBtn.setText("Autobox");
        autoboxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoboxBtnActionPerformed(evt);
            }
        });

        castBtn.setText("Cast");
        castBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcBtn)
                        .addGap(18, 18, 18)
                        .addComponent(typesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(numRangesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(autoboxBtn)
                        .addGap(18, 18, 18)
                        .addComponent(castBtn)
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcBtn)
                    .addComponent(typesBtn)
                    .addComponent(numRangesBtn)
                    .addComponent(autoboxBtn)
                    .addComponent(castBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        Integer i;
        Double d1;        
        Double d2;
        d1 = 105.123;
        i = d1.intValue(); 
        d2 = i.doubleValue();
        outputTA.setText("i = " + i + ", d1 = " + d1 + ", d2 = " + d2);
    }//GEN-LAST:event_calcBtnActionPerformed

    private void typesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typesBtnActionPerformed
        String msg;
        
        byte b;
        short s;
        int i;
        long l;
        
        float f;
        double d;
        
        char c;
        
        boolean bool;
        
        b = 127;
        s = 32767;
        i = 2147483647;        
        l = 922337203685477580L;  // Literals are int by default - I need the L
                                  // suffix to make it long  
        f = 3.4028235E38F;        // terminating F makes this a float        
        d = 1.7976931348623157E308;
        
        c = 'x';
        bool = true;
        
      /*   msg =   "byte b = " + Byte.toString(b) +
                "\nshort s = " + Short.toString(s) +
                "\nint i = " + Integer.toString(i) +
                "\nlong l = " + Long.toString(l) +
                "\nfloat f = " + Float.toString(f) +
                "\ndouble d = " + Double.toString(d) +
                "\nchar c = " + Character.toString(c) +
                "\nboolean bool = " + Boolean.toString(bool);
        */
        
        // in fact, this code could be used as objects that are not strings
        // will be auto-converted by calling toString() for each object
        // during concatenation
        msg =   "byte b = " + b +
                "\nshort s = " + s +
                "\nint i = " + i +
                "\nlong l = " + l +
                "\nfloat f = " + f +
                "\ndouble d = " + d +
                "\nchar c = " + c +  
                "\nboolean bool = " + bool;
        outputTA.setText(msg);
    }//GEN-LAST:event_typesBtnActionPerformed

    private void numRangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numRangesBtnActionPerformed
        String msg;
        msg = "Min byte value   = " + Byte.MIN_VALUE +
        "\nMax byte value   = " + Byte.MAX_VALUE + 
        "\nMin short value  = " + Short.MIN_VALUE +
        "\nMax short value  = " + Short.MAX_VALUE +
        "\nMin int value    = " + Integer.MIN_VALUE +
        "\nMax int value    = " + Integer.MAX_VALUE + 
        "\nMin long value    = " + Long.MIN_VALUE +
        "\nMax long value    = " + Long.MAX_VALUE +
        "\nMin float value  = " + Float.MIN_VALUE +
        "\nMax float value  = " + Float.MAX_VALUE +
        "\nMin double value = " + Double.MIN_VALUE +
        "\nMax double value = " + Double.MAX_VALUE;
        outputTA.setText(msg);
    }//GEN-LAST:event_numRangesBtnActionPerformed

    private void autoboxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoboxBtnActionPerformed
        String msg;
        
        Integer boxedInt;
        int unboxedInt;
        
        Double boxedDouble;
        double unboxedDouble;                       
       
        // autobox primitives into Integer and Double objects
        boxedInt = 500;         // auto-boxing
        boxedDouble = 200.25;
        
        unboxedInt = boxedInt;  // auto-unboxing
        unboxedDouble = boxedDouble;        
        
        msg = "boxedInt = " + boxedInt + ", unBoxedInt = " + unboxedInt +
              "\nboxedDouble = " + boxedDouble + ", unBoxedDouble = " + unboxedDouble ;
        
        outputTA.setText(msg);
    }//GEN-LAST:event_autoboxBtnActionPerformed

    private void castBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castBtnActionPerformed
        float floatVar;
        double doubleVar;
        doubleVar = 1.765987009800000052;
        floatVar = (float)doubleVar;        
        outputTA.setText("doubleVar = " + doubleVar + ", floatVar = " + floatVar);        
    }//GEN-LAST:event_castBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoboxBtn;
    private javax.swing.JButton calcBtn;
    private javax.swing.JButton castBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton numRangesBtn;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton typesBtn;
    // End of variables declaration//GEN-END:variables
}
