/*
 * Bitwise Courses - sample Java code
 * http://www.bitwisecourses.com
 */

/**
 *
 * @author huw
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        userinput = new javax.swing.JTextField();
        testBtn = new javax.swing.JButton();
        moreTestsBtn = new javax.swing.JButton();
        complexTestsBtn = new javax.swing.JButton();
        numericalTestsBtn = new javax.swing.JButton();
        nameinput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        userinput.setText("hello");

        testBtn.setText("Test");
        testBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnActionPerformed(evt);
            }
        });

        moreTestsBtn.setText("More Tests");
        moreTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreTestsBtnActionPerformed(evt);
            }
        });

        complexTestsBtn.setText("Complex Tests");
        complexTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complexTestsBtnActionPerformed(evt);
            }
        });

        numericalTestsBtn.setText("Numerical Tests");
        numericalTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numericalTestsBtnActionPerformed(evt);
            }
        });

        nameinput.setText("Fred");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userinput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(testBtn)
                                .addGap(18, 18, 18)
                                .addComponent(moreTestsBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(complexTestsBtn)
                                .addGap(18, 18, 18)
                                .addComponent(numericalTestsBtn))
                            .addComponent(nameinput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {complexTestsBtn, moreTestsBtn, numericalTestsBtn, testBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testBtn)
                    .addComponent(moreTestsBtn)
                    .addComponent(complexTestsBtn)
                    .addComponent(numericalTestsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnActionPerformed
        String inputStr;
        inputStr = userinput.getText();
        if (inputStr.equals("")) {
            output.setText("You didn't enter anything");            
        } else if ((inputStr.equals("hello")) || (inputStr.equals("hi"))) {
            output.setText("Hello to you too!");
        } else {
            output.setText("I don't understand that!");
        }
    }//GEN-LAST:event_testBtnActionPerformed

    private void moreTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreTestsBtnActionPerformed
        String inputStr;
        inputStr = userinput.getText();
        switch (inputStr) {
            case "":
                output.setText("You didn't enter anything");
                break;
            case "hello":
            case "hi":
                output.setText("Hello to you too!");
                break;
            default:
                output.setText("I don't understand that!");
                break;
        }
    }//GEN-LAST:event_moreTestsBtnActionPerformed

    private void complexTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complexTestsBtnActionPerformed
        String msg;
        String name;
        int msglen;
        int namelen;
        msg = userinput.getText();
        name = nameinput.getText();
        msglen = msg.length();
        namelen = name.length();
        if ((msglen == 0) && (namelen == 0)) {
            output.setText("You haven't entered anything!");
        } else if ((msglen == 0) || (namelen == 0)) {
            output.setText("You must enter something into both text boxes");
        } else if ((!msg.equals("hi")) && (!msg.equals("hello"))) {
            output.setText("Please enter a friendly greeting ('hi' or 'hello' would be nice)");
        } else {
            output.setText("Well, " + msg + " to you too, " + name);
        }
    }//GEN-LAST:event_complexTestsBtnActionPerformed

    private void numericalTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numericalTestsBtnActionPerformed
        /*
         * Try different tests such as:
         * i == i
         * i < j
         * i <= j
         * i > j
         * i >= j
         * i != j
         * i != i
         * */
        int i = 100;
        int j = 200;
        if (i != j) {
            output.setText("Test is true");
        } else {
            output.setText("Test is false");
        }

    }//GEN-LAST:event_numericalTestsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complexTestsBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moreTestsBtn;
    private javax.swing.JTextField nameinput;
    private javax.swing.JButton numericalTestsBtn;
    private javax.swing.JTextArea output;
    private javax.swing.JButton testBtn;
    private javax.swing.JTextField userinput;
    // End of variables declaration//GEN-END:variables
}
