
import java.util.ArrayList;

/*
 * Bitwise Courses - sample Java code
 * http://www.bitwisecourses.com
 */

/**
 *
 * @author huw
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        stringListBtn = new javax.swing.JButton();
        genericStringListBtn = new javax.swing.JButton();
        myListBtn = new javax.swing.JButton();
        myListIntegerBtn = new javax.swing.JButton();
        myGenClass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        stringListBtn.setText("string list");
        stringListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringListBtnActionPerformed(evt);
            }
        });

        genericStringListBtn.setText("generic string list");
        genericStringListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genericStringListBtnActionPerformed(evt);
            }
        });

        myListBtn.setText("MyList (String)");
        myListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myListBtnActionPerformed(evt);
            }
        });

        myListIntegerBtn.setText("MyList (Integer)");
        myListIntegerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myListIntegerBtnActionPerformed(evt);
            }
        });

        myGenClass.setText("My Generic Class");
        myGenClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGenClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stringListBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genericStringListBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(myListIntegerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(myListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(myGenClass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringListBtn)
                    .addComponent(myListBtn)
                    .addComponent(myGenClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genericStringListBtn)
                    .addComponent(myListIntegerBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList aList = new ArrayList();   
    ArrayList <String>gStrList = new ArrayList<>();
    MyList<String>sList = new MyList<>();
    MyList<Integer>iList = new MyList<>();
    
    private String getLastItem(ArrayList aList){
        return (String) aList.get(aList.size()-1);
    }
    
    private String getLastStrItem(ArrayList<String> aList){
        return aList.get(aList.size()-1);
    }          
    
    private void stringListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringListBtnActionPerformed
        aList.add("one");
        aList.add(2);
        aList.add("three");
       // aList.add(4);
        outputTA.append(getLastItem(aList) + "\n");               
    }//GEN-LAST:event_stringListBtnActionPerformed

    private void genericStringListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genericStringListBtnActionPerformed
        gStrList.add("one");
       // gStrList.add(2);
        gStrList.add( "two" );
        gStrList.add("three");        
        outputTA.append(getLastStrItem(gStrList) + "\n");
    }//GEN-LAST:event_genericStringListBtnActionPerformed

    private void myListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myListBtnActionPerformed
        sList.add("one");
       // sList.add(2);
        sList.add("two");
        sList.add("three");        
        outputTA.append(sList.getLastItem() + "\n");
    }//GEN-LAST:event_myListBtnActionPerformed

    private void myListIntegerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myListIntegerBtnActionPerformed
         iList.add(1);
       // iList.add("two");
        iList.add(2);
        iList.add(3);            
        outputTA.append(iList.getLastItem().toString() + "\n");        
    }//GEN-LAST:event_myListIntegerBtnActionPerformed

    private void myGenClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGenClassActionPerformed
        MyGenericClass<String> myStrOb = new MyGenericClass<>("Hello world");
        MyGenericClass<Integer> myIntegerOb = new MyGenericClass<>(10);
        outputTA.append(myStrOb.describe());
        outputTA.append(myIntegerOb.describe());
        myIntegerOb.setSomeData(500);
        outputTA.append(myIntegerOb.describe());        
    }//GEN-LAST:event_myGenClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genericStringListBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton myGenClass;
    private javax.swing.JButton myListBtn;
    private javax.swing.JButton myListIntegerBtn;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton stringListBtn;
    // End of variables declaration//GEN-END:variables
}
